### PR TITLE
make: consistent time reporting and colouring

### PR DESCRIPTION
**Pull request by tiborsimko**
* make: consistent time reporting and colouring

Reports time and uses colours consistently for both ``make`` commands
and ``reana-dev`` commands.

Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>   

* make: tiny sleep to make CI pass

Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
Note: tested on dark scheme on GNU/Linux. People on macOS, using light or dark theme, can you please check whether this looks reasonably OK on your setups? @diegodelemos @leticiawanderley @okraskaj @roksys

Here's screenshot from my system how it is supposed to look for comparison:

2019-07-29-164432_2560x1440_scrot

**Comment by roksys** [comment]
Screenshot 2019-07-31 at 14 45 20
 
That's how it looks light theme.

**Comment by tiborsimko** [comment]
@roksys Thanks, so macOS mostly works (modulo first light grey), note that you also need to do `pip install . --upgrade` in the `reana` repository in order to have the colours right for inner CLI statements.

**Comment by tiborsimko** [comment]
The first light grey commanad should be now fixed.

**Comment by roksys** [comment]
Screenshot 2019-08-09 at 11 49 52

**Comment by tiborsimko** [comment]
@roksys You still need to do `pip install . --upgrade` from this PR in order to have good inner colours everywhere :wink:

**Comment by roksys** [comment]
@tiborsimko, I did that.

**Pull request merged**
