### PR TITLE
cli: support for several cluster modes

### PR DESCRIPTION
**Pull request by tiborsimko**
Current status:

### CODE REVIEW

**Comment by tiborsimko** [comment]
Current status:

- mode=development ... OK
- mode=debug ......... OK
- mode=production .... OK (but workflows not consumed; need a new reana-commons release and updates)
- mode=helm .......... OK (but currently error; see below; can be fixed for next helm chart release)
 
```
2020-07-21 12:03:44,180 | reana_commons.k8s.secrets | Thread-2 | ERROR | Something went wrong while retrieving Kubernetes secret for user reana-secretsstore-00000000-0000-0000-0000-000000000000.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/reana_commons/k8s/secrets.py", line 70, in _get_k8s_user_secrets_store
    K8S_DEFAULT_NAMESPACE)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 20110, in read_namespaced_secret
    (data) = self.read_namespaced_secret_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 20201, in read_namespaced_secret_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 366, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 241, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 21 Jul 2020 12:03:44 GMT', 'Content-Length': '415'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"reana-secretsstore-00000000-0000-0000-0000-000000000000\" is forbidden: User \"system:serviceaccount:default:default\" cannot get resource \"secrets\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"name":"reana-secretsstore-00000000-0000-0000-0000-000000000000","kind":"secrets"},"code":403}


2020-07-21 12:03:44,185 | reana_job_controller.factory | Thread-2 | ERROR | Exception on /jobs [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/reana_job_controller/rest.py", line 208, in create_job
    backend_jod_id = job_obj.execute()
  File "/usr/local/lib/python3.6/site-packages/reana_job_controller/job_manager.py", line 59, in wrapper
    backend_job_id = fn(inst, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/reana_job_controller/kubernetes_job_manager.py", line 131, in execute
    secret_env_vars = secrets_store.get_env_secrets_as_k8s_spec()
  File "/usr/local/lib/python3.6/site-packages/reana_commons/k8s/secrets.py", line 164, in get_env_secrets_as_k8s_spec
    all_secrets = self.get_secrets()
  File "/usr/local/lib/python3.6/site-packages/reana_commons/k8s/secrets.py", line 145, in get_secrets
    for secret_name in secrets_store.data:
AttributeError: 'NoneType' object has no attribute 'data'
2020-07-21 12:03:44,186 | werkzeug | Thread-2 | INFO | 127.0.0.1 - - [21/Jul/2020 12:03:44] "POST /jobs HTTP/1.1" 500 -

```

**Comment by diegodelemos** [comment]
Works fine for me, just two observations:
- I would perhaps rename `helm` to `production` and `production` to `stable` or similar. It is just that `helm` mode sounds a bit confusing since all installations use Helm in any case.
- I like it better than the previous approach, the only thing I miss is a piece of documentation that shows what each mode is/does. The command line option help might not be the best place since this could be potentially multiline? What do you think?

**Comment by tiborsimko** [comment]
As for the first two names:

- WRT `helm`, I agree it is not exact.The mode is basically using released charts and images without any building; so it only calls `helm`, as it were. I wanted to call it `helmonly`, but it seemed a bit weird? A good candidate could be "release", but:

- WRT `production`, it is building everything using `r-commons` etc shared modules from PyPI, i.e. no submodules. This is also "release", but not "helm-release", rather "pypi-release". Hence the naming difficulty.

Otherwise:

- "development" adds locally checked-out r-commons and friends; we are good here.

- "debug" adds live code mounting and wdb; we are good here.

The naming trouble is because we have three kinds of releases: helm-release, docker-release, pypi-release.  We could even use these names literally as modes, giving "helmrelease -> dockerrelease -> pypirelease -> latest -> debug".  (we could add the "dockerrelease" mode later, which would be suitable for developing Helm charts without building images; and "latest" to indicate this mode uses always latest tip of each source code repository)

Possible name chains:

- helm -> production -> development -> debug     *(current bad names)*
- release -> latest -> development -> debug         *(latest can be ambiguous here)*
- release -> stable -> unstable -> debug               *(perhaps ok?)*
- releasehelm -> releasepypi -> latest -> debug   *(perhaps the most precise?)*
- ...

P.S. For the second point, yes the modes will get documented in the docs.reana.io extensively, instead of `make` that we have there now, once we merge the Kind branch to `master`.

**Comment by diegodelemos** [comment]
I agree that `releasehelm -> releasepypi -> latest -> debug` is the most precise option. Although it sounds a bit weird, it follows the Zen of Python "Explicit is better than implicit." I prefer it. Just last proposal what about `master` instead of `latest` (again being more explicit than implicit).

**Comment by tiborsimko** [comment]
> what about master instead of latest

When you work on feature branches, or on maint-0.6 fixes, people may have checked out various branches locally, and `master` could give wrong impression that this would be building out of `master` branch of all components.  

Hence I preferred `latest` which says that we shall be building `latest` docker images, using whatever latest tip is being checked out locally. 

Come to think of it, we could also use `local` as the name of the mode, and `localdebug` for the fourth mode :)  

*"There are only two hard things in Computer Science: cache invalidation and naming things." --Phil Karlton*

**Comment by diegodelemos** [comment]
> When you work on feature branches, or on maint-0.6 fixes, people may have checked out various branches locally, and master could give wrong impression that this would be building out of master branch of all components.

That's right.. then I would stay with `latest`, since `local` would make it look a bit weird with the `localdebug` option. I am sold for `releasehelm -> releasepypi -> latest -> debug ` 😄 .

**Pull request merged**
