### PR TITLE
Update gettingstarted.rst

### PR DESCRIPTION
**Pull request by longr**
Corrected spelling mistake in flag.

### CODE REVIEW

**Comment by tiborsimko** [comment]
@longr Thanks! As this is your first contribution to REANA, can you please reply to this PR with a comment that you agree to donate this (and any future) contributions to the reanahub organisation under the terms of the corresponding FLOSS licenses we use? (GNU GPLv3+, MIT...) Sorry for the explicit legalese and thanks for your understanding :)

**Comment by tiborsimko** [comment]
You can also amend this PR to add yourself to the list of REANA contributors in `AUTHORS.rst` file with your ORCID.

**Comment by longr** [comment]
@tiborsimko Thanks. I agree to these terms. (Is that enough or do you need something more specific).

**Comment by tiborsimko** [comment]
Thanks, I have corrected one more occurrence of `incude` in another guide, I have added you to the list of contributors pointing to your GitHub page (if you have ORCID please fix), otherwise everything is OK :+1:

**Pull request merged**
